// Load .env only when not running inside Lambda/production
if (!process.env.AWS_LAMBDA_FUNCTION_NAME && !process.env.LAMBDA_TASK_ROOT) {
  require("dotenv").config();
}
// cookie
const COOKIE_ENABLED = true,COOKIE_DISABLED = false;
// db
const TTL=0.5, INSERT= false, MAX_CONNECTIONS = 40;
// base url
const { 
  GET_API_FUTURE_2,
  EXCHANGE,EXCHANGE2,
  GET_API_1,GET_API_2,
  BASE_URL,BASE_URL_2,
  PAGE_URL_1,PAGE_URL_2,
  GET_API_ACTIVE_1,GET_API_ACTIVE_2,
  DYNAMO_DB_TABLE_1,DYNAMO_DB_TABLE_2,
  PAGE_ACTIVE_URL_1,PAGE_ACTIVE_URL_2,
} = process.env;

module.exports = {
  GET_API_FUTURE_2,
  EXCHANGE,EXCHANGE2,
  BASE_URL,BASE_URL_2,
  GET_API_1,GET_API_2,
  PAGE_URL_1,PAGE_URL_2,
  TTL,INSERT,MAX_CONNECTIONS,
  GET_API_ACTIVE_1,GET_API_ACTIVE_2,
  DYNAMO_DB_TABLE_1,DYNAMO_DB_TABLE_2,
  PAGE_ACTIVE_URL_1,PAGE_ACTIVE_URL_2,
  COOKIE_ENABLED,COOKIE_DISABLED
};
